##AI/ML Assignment 1
###Task - 1 Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [1]:
import pandas as pd
import numpy as np


np.random.seed(50)
data = np.random.rand(4, 4)

df = pd.DataFrame(data)

df.columns=['Feature 1','Feature 2', 'Feature 3', 'Feature 4']
df.index=['Observation 1', 'Observation 2', 'Observation 3', 'Observation 4']
df

               Feature 1  Feature 2  Feature 3  Feature 4
Observation 1   0.494602   0.228083   0.255474   0.396330
Observation 2   0.377315   0.996574   0.408197   0.771894
Observation 3   0.760537   0.310009   0.346541   0.351765
Observation 4   0.145467   0.972665   0.909178   0.559957

###Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [2]:
import pandas as pd
import numpy as np


np.random.seed(50)
data = np.random.rand(4, 4)

df = pd.DataFrame(data)

df.columns=['Feature 1','Feature 2', 'Feature 3', 'Feature 4']
df.index=['Observation 1', 'Observation 2', 'Observation 3', 'Observation 4']
df=df.rename(columns={'Feature 1': 'Random value 1',
                      'Feature 2': 'Random value 2',
                      'Feature 3': 'Random value 3',
                      'Feature 4': 'Random value 4'})
df

               Random value 1  Random value 2  Random value 3  Random value 4
Observation 1        0.494602        0.228083        0.255474        0.396330
Observation 2        0.377315        0.996574        0.408197        0.771894
Observation 3        0.760537        0.310009        0.346541        0.351765
Observation 4        0.145467        0.972665        0.909178        0.559957

###Find the descriptive statistics of the 'df' dataframe

In [3]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.444480        0.626833        0.479848        0.519986
std          0.255815        0.414603        0.293015        0.190302
min          0.145467        0.228083        0.255474        0.351765
25%          0.319353        0.289528        0.323774        0.385189
50%          0.435958        0.641337        0.377369        0.478144
75%          0.561085        0.978642        0.533443        0.612941
max          0.760537        0.996574        0.909178        0.771894

###Check for the null values in 'df' and find the data type of the columns.

In [8]:
null_value = df.isnull().sum()
col_datatypes = df.dtypes
print("Null Values:")
print(null_value)
print("\nColumn Data Types:")
col_datatypes

Null Values:
Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

Column Data Types:

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

###Display the 'Random value 2' & 'Random value 3' columns with location method and index location method

In [9]:
print("Using .loc[]:")
print(df.loc[:, ['Random value 2', 'Random value 3']])
print("\nUsing .iloc[]:")
print(df.iloc[:, [1, 2]])

Using .loc[]:
               Random value 2  Random value 3
Observation 1        0.228083        0.255474
Observation 2        0.996574        0.408197
Observation 3        0.310009        0.346541
Observation 4        0.972665        0.909178

Using .iloc[]:
               Random value 2  Random value 3
Observation 1        0.228083        0.255474
Observation 2        0.996574        0.408197
Observation 3        0.310009        0.346541
Observation 4        0.972665        0.909178